spring.application.name=lyricsflow_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/LyricsFlow
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true
