@baseUrl = http://localhost:8080/tasks

### Gerar tarefa
POST {{baseUrl}}/start
Content-Type: application/json

{
    "userId": 11,
    "songId": 3
}

### Enviar resposta
POST {{baseUrl}}/submit
Content-Type: application/json

{
    "taskId": 27,
    "userId": 11,
    "userAnswers": [
        "desert",
        "wind",
        "sme",
        "light",
        "heavy",
        "doorway",
        "bell",
        "heaven",
        "place",
        "room",
        "friends",
        "remember"
    ]
}